name: Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      FIREBASE_TOKEN:
        required: true

jobs:
  run-cd:
    name: Deploy to firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 16
            cache: 'yarn'

      - name: Install node_modules & firebase-tools
        run: |
          yarn install --frozen-lockfile
          yarn global add firebase-tools@11.27.0

      - name: Deployment to ${{ inputs.ENVIRONMENT }}
        run: |
          firebase experiments:enable webframeworks
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

