name: Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      FIREBASE_TOKEN:
        required: true

jobs:
  run-cd:
    name: Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 14
            cache: 'yarn'

      - name: Install node_modules and firebase-tools
        run: |
          npm install -g firebase-tools

      - name: Deployment to ${{ inputs.ENVIRONMENT }}
        run: |
          firebase experiments:enable webframeworks
          firebase deploy ---only hosting

