name: release-please

on:
  workflow_dispatch:
    inputs:
      force_release:
        description: force deployment
        default: "false"
        required: false
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  ci-check:
    uses: ./.github/workflows/ci.yml

  release-please:
    runs-on: ubuntu-latest
    needs: [ci-check]
    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: cracker-app

  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    needs: [release-please]
    if: inputs.force_release == 'true' || needs.release-please.outputs.release_created == 'true'
    with:
      environment: prod
    secrets: inherit

